repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: ["--config=pyproject.toml"]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--config=pyproject.toml"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies: []
        args: ["--config-file", "mypy.ini", "src"]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest -n auto --cov=src --cov-report=term-missing -q
        language: system
        types: [python]
