[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fueltracker"
version = "0.1.0"
description = "Fuel tracker sample application"
requires-python = ">=3.11"
authors = [{name="Example", email="example@example.com"}]
dependencies = [
    "PySide6>=6.7",
    "SQLModel>=0.0.16",
    "pandas",
    "fpdf2",
    "matplotlib",
    "python-dotenv",
    "alembic",
    "reportlab",
    "win10toast; sys_platform == 'win32'",
    "requests",
    "keyboard",
    "openpyxl",
    "pydantic-settings",
    "types-keyboard",
    "types-reportlab",
    "types-requests",
]
[project.optional-dependencies]
dev = [
    "poethepoet",
]
[project.scripts]
fueltracker = "fueltracker.main:run"

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88

[tool.poe.tasks.lint]
sequence = ["ruff", "mypy", "vulture"]

[tool.poe.tasks.test]
cmd = "pytest -q"

[tool.poe.tasks.migrate]
cmd = "python -m fueltracker migrate"

[tool.poe.tasks.runtime-check]
cmd = "python -m fueltracker --check"
env = { QT_QPA_PLATFORM = "offscreen" }

[tool.poe.tasks.build]
cmd = "pyinstaller --noconfirm --noconsole --name FuelTracker --icon assets/icon.ico src/fueltracker/__main__.py"

[tool.poe.tasks.validate]
sequence = ["lint", "migrate", "test", "runtime-check"]
